# Generated by Django 3.1.1 on 2020-09-10 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории новостей'},
        ),
        migrations.AlterField(
            model_name='new',
            name='publish_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 10, 12, 43, 3, 69703, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
